kjvarga/sitemap_generator

lib/sitemap_generator/adapters/s3_adapter.rb

This makes it possible to use the fog-aws gem to allow sitemaps to be
uploaded to s3, rather than using the root fog gem. fog-aws has far
fewer dependencies than the fog gem itself so is the preferred option in
projects that don't already have fog as a dependency.

Require 'fog/storage' rather than 'fog'

---

lib/sitemap_generator/adapters/s3_adapter.rb

Using IAM instance role profile instead of setting access key & secret is recommended by AWS as security best practice.

Supports AWS IAM profile

---

lib/sitemap_generator.rb

`SitemapGenerator::Sitemap` implementation is based on `method_missing`, but it didn't have proper `respond_to?` implementation. 
For this reason, e.g., it didn't play well with RSpec mocking with `verify_partial_doubles = true`.

Implement respond_to? in SitemapGenerator::Sitemap

---

README.md
lib/sitemap_generator/builder/sitemap_url.rb
spec/sitemap_generator/alternate_sitemap_spec.rb

In AppIndexing, `hreflang` is not a required element.
https://developers.google.com/app-indexing/reference/deeplinks

Change 'hreflang' to optional element

---

README.md
lib/sitemap_generator.rb
lib/sitemap_generator/adapters/aws_sdk_adapter.rb

An alternate adapter to the S3Adapter for those using the plain old
bare 'aws-sdk' gem without 'fog'. This class modelled on that adapter
but also sets up the S3 object to return the following additional HTTP
headers:
* Cache-Control: private, max-age=0, no-cache
* Content-Type: application/x-gzip
for completeness.
No integration test created, as noted in the s3_adapter_spec.rb, it
would be of limited use.
IAM authentication is not yet supported.

AWS S3 adapter using the bare aws-sdk gem

---

lib/sitemap_generator/railtie.rb

Reason for the change:
I am trying to run `Rake::Task["sitemap:refresh"]` from a resque background job. But I get `RuntimeError Don't know how to build task 'sitemap:refresh'`
Based on http://edgeapi.rubyonrails.org/classes/Rails/Railtie.html#class-Rails::Railtie-label-Loading+rake+tasks+and+generators

Load the rake task instead of requiring them

---

README.md
lib/capistrano/tasks/sitemap_generator.cap

Since the task `deploy` is quite exclusive to Capistrano, we should use Sitemap Generator's own namespace instead, so not to be confused with Capistrano's `deploy`.

Use Sitemap namespace for Capistrano

---

lib/sitemap_generator/adapters/s3_adapter.rb

Inline rescue fails to actually capture the LoadError exception.
```
pry(main)> require 'fog/core/services_mixin' rescue nil
LoadError: cannot load such file -- fog/core/services_mixin
```
Tested under Ruby 2.3.3.

Fix up workaround for fog-core 1.2.0

---

lib/sitemap_generator/adapters/aws_sdk_adapter.rb

In the current behavior, you can not use instance profiles and task role in the instance that creates the sitemap.
aws-sdk-ruby v2 is auto detected using credentials.
According to the behavior of aws-sdk-ruby v2 unless you specify anything, explicitly specify that you use the specified credentials.
https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/credential_provider_chain.rb#L10-L16
Backwards compatibility is preserved because environment variables are used in the default behavior of aws-sdk-ruby v2.
thanks

AwsSdkAdapter default using aws-sdk-ruby default credential resolver

---

lib/sitemap_generator/core_ext/big_decimal.rb

Testing this against Ruby 2.4, I observe following test error:
~~~
1) SitemapGenerator::BigDecimal to_yaml should serialize correctly
Failure/Error:
YAML.quick_emit(nil, opts) do |out|
string = to_s
out.scalar(YAML_TAG, YAML_MAPPING[string] || string, :plain)
end
TypeError:
can't define singleton method "encode_with" for SitemapGenerator::BigDecimal
~~~
This happens because YAML::ENGINE is not available since Ruby 2.0.0+, when Syck was removed
from stdlib and replaced by Psych.
However, I am not sure if this is Ruby 1.8.7 compatible and if you care about it ...

Fix Ruby 2.0.0+ compatibility.

---

lib/sitemap_generator/core_ext/big_decimal.rb

Replace `yaml_as` with `yaml_tag` as directed by the deprecation warning. This allows sitemap_generator to work with Ruby 2.5.0. 🎉
I also ran the specs using Ruby 2.5.0 just to be sure – everything passes.
Fixes #297.

Use `yaml_tag` instead of `yaml_as`, which was deprecated in Ruby 2.4 and removed in 2.5

---

README.md

Hi @kjvarga,
First, thank you very much for maintaining this gem. I've been using it for years now and it never gave me any problems, as it's truly feature complete 👏.
This PR aims to add a small piece of info at the README, explaining to Rails users that they don't need to require the `sitemap_generator/tasks` file as explained on the previous Ruby Installation section.
A colleague happened to notice the sitemap generation was happening twice, and I noticed I've added the `require 'sitemap_generator/tasks'` on my Rails project Rakefile. SitemapGenerator was calling the config file twice because of this :)
Investigating a bit, I found the autoloading:
here:
https://github.com/kjvarga/sitemap_generator/blob/a6edcf5d8974d3450882bb6b9e12e33e01542f8d/lib/sitemap_generator.rb#L85 
and here: …

Add explanation about rake tasks autoloading on Rails

---

README.md

The config block has been moved from environment.rb to application.rb some years back

Fix rails instructions in README

---

lib/sitemap_generator/core_ext/big_decimal.rb

Because BigDecimal.new has been deprecated in favor of Kernel.BigDecimal
just as other Ruby core Numeric classes.
This eliminates the following warning:
> warning: BigDecimal.new is deprecated; use Kernel.BigDecimal method instead.

Prefer composition over inheritance with BigDecimal

---

lib/sitemap_generator.rb
lib/sitemap_generator/adapters/file_adapter.rb
lib/sitemap_generator/builder/sitemap_index_file.rb
lib/sitemap_generator/link_set.rb
lib/sitemap_generator/templates.rb
spec/support/file_macros.rb

Here are fixes for some Ruby warnings that we see in our app.

Ruby Warnings

---

README.md
lib/sitemap_generator.rb
lib/sitemap_generator/adapters/google_storage_adapter.rb
sitemap_generator.gemspec
spec/sitemap_generator/adapters/google_storage_adapter_spec.rb

Hi @kjvarga,
I have added `GoogleStorageAdapter` to support remote uploads Google Cloud Storage. Pease review the PR. I am already using this in one of my application, so I know that this works. I saw an issue for Google Storage so I thought I'd help out.
Let me know if there's an issue.

Add google storage support for remote uploads

---

lib/sitemap_generator/link_set.rb

Fixes https://github.com/kjvarga/sitemap_generator/issues/352
`NoMethodError: private method 'open' called for URI:Module` was raised on older rubies as `URI.open` was added only in Ruby 2.5: https://rubyreferences.github.io/rubychanges/2.5.html#network-and-web

Fix NoMethodError error on Ruby 2.4 and older. 

---

lib/sitemap_generator/adapters/google_storage_adapter.rb

Due to [ruby 3 changes to kwargs](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) the arguments of the hash were no longer being accepted on the GCloud initializer. Use the double splat operator to fix this issue
Hope to fix issue https://github.com/kjvarga/sitemap_generator/issues/371

Update google cloud adapter to support ruby 3 kwarg changes

---

CHANGES.md
README.md
lib/sitemap_generator/adapters/aws_sdk_adapter.rb
spec/sitemap_generator/adapters/aws_sdk_adapter_spec.rb

From https://github.com/kjvarga/sitemap_generator/pull/405 and https://github.com/kjvarga/sitemap_generator/pull/394

allow setting acl and cache_control when uploading to s3

---

CHANGES.md
README.md
lib/sitemap_generator/adapters/google_storage_adapter.rb
spec/sitemap_generator/adapters/google_storage_adapter_spec.rb

From https://github.com/kjvarga/sitemap_generator/pull/397

Add acl option to GCS adapter

---

lib/sitemap_generator.rb
lib/sitemap_generator/adapters/aws_sdk_adapter.rb
lib/sitemap_generator/adapters/file_adapter.rb
lib/sitemap_generator/adapters/fog_adapter.rb
lib/sitemap_generator/adapters/google_storage_adapter.rb
lib/sitemap_generator/adapters/s3_adapter.rb
lib/sitemap_generator/adapters/wave_adapter.rb
lib/sitemap_generator/application.rb
lib/sitemap_generator/builder.rb
lib/sitemap_generator/builder/sitemap_file.rb
lib/sitemap_generator/builder/sitemap_index_file.rb
lib/sitemap_generator/builder/sitemap_index_url.rb
lib/sitemap_generator/builder/sitemap_url.rb
lib/sitemap_generator/core_ext.rb
lib/sitemap_generator/core_ext/big_decimal.rb
lib/sitemap_generator/core_ext/numeric.rb
lib/sitemap_generator/helpers/number_helper.rb
lib/sitemap_generator/interpreter.rb
lib/sitemap_generator/link_set.rb
lib/sitemap_generator/railtie.rb
lib/sitemap_generator/simple_namer.rb
lib/sitemap_generator/sitemap_location.rb
lib/sitemap_generator/tasks.rb
lib/sitemap_generator/templates.rb
lib/sitemap_generator/utilities.rb

Add "frozen_string_literal: true" magic header

---

lib/sitemap_generator/templates.rb

This PR adds binding and line number information to an eval'd piece of code.

Ensure eval call knows its line numbers etc

---

README.md

This PR replaces the CircleCI build status badge.

README: use GitHub Actions build status badge

---

lib/sitemap_generator/templates.rb

When Ruby warnings are enabled, this is printed when loading the sitemap_generator gem:
> sitemap_generator-6.3.0/lib/sitemap_generator/templates.rb:16):1: warning: method redefined; discarding old sitemap_sample
This is because an attr reader (e.g. `sitemap_sample`) was being defined via `attr_accessor` and then immediately redefined with `define_method`.
Fix by using `attr_writer` instead of `attr_accessor`, so that the attr reader is not defined twice.

Fix Ruby "method redefined" warning

---

lib/sitemap_generator/adapters/aws_sdk_adapter.rb
lib/sitemap_generator/adapters/s3_adapter.rb
spec/sitemap_generator/adapters/s3_adapter_spec.rb

I tried to use on AWS Lambda and needed to patch a little bit. Instead of fetching metadata like EC2 or ECS, AWS Lambda initially has `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN` from the beginning, as reserved environment variables. In this case, we need to pass these variables directly into fog or `Aws::S3::Resource`.

Support AWS Lambda

---

README.md
lib/sitemap_generator/link_set.rb
spec/sitemap_generator/link_set_spec.rb

See: https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping

Google ping is deprecated
